// Generated by Framer (0320f5c)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    Link,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/q1c7qEJuRlokzN3qCOiO/Tm5MxxE4i1fD0zNA9Vr5/AqofocsPm.js";
const enabledGestures = {
    OvfEy1I7B: {
        hover: true
    },
    Xopd_EfEJ: {
        hover: true
    }
};
const cycleOrder = ["Xopd_EfEJ", "OvfEy1I7B"];
const serializationHash = "framer-5VmjC";
const variantClassNames = {
    OvfEy1I7B: "framer-v-qxphcx",
    Xopd_EfEJ: "framer-v-1m42knt"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 60,
    delay: 0,
    mass: 1,
    stiffness: 500,
    type: "spring"
};
const transition2 = {
    damping: 40,
    delay: 0,
    mass: 1,
    stiffness: 500,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Default: "Xopd_EfEJ",
    Inverse: "OvfEy1I7B"
};
const getProps = ({
    click,
    height,
    id,
    link,
    newTab,
    smoothScroll,
    title,
    width,
    ...props
}) => {
    return { ...props,
        GY5rHEk7n: smoothScroll ? ? props.GY5rHEk7n,
        JzvcOuD__: newTab ? ? props.JzvcOuD__,
        NTOnIbDOf: link ? ? props.NTOnIbDOf,
        oTGribf8Y: click ? ? props.oTGribf8Y,
        Q0n_gFqmK: title ? ? props.Q0n_gFqmK ? ? "Item",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "Xopd_EfEJ"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        Q0n_gFqmK,
        NTOnIbDOf,
        JzvcOuD__,
        GY5rHEk7n,
        oTGribf8Y,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "Xopd_EfEJ",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap19umq78 = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (oTGribf8Y) {
            const res = await oTGribf8Y(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: NTOnIbDOf,
                    motionChild: true,
                    nodeId: "Xopd_EfEJ",
                    openInNewTab: JzvcOuD__,
                    scopeId: "FWoRjh02q",
                    smoothScroll: GY5rHEk7n,
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-1m42knt",className,classNames)} framer-1l20qc7`,
                        "data-framer-name": "Default",
                        "data-highlight": true,
                        layoutDependency: layoutDependency,
                        layoutId: "Xopd_EfEJ",
                        onTap: onTap19umq78,
                        ref: refBinding,
                        style: { ...style
                        },
                        ...addPropertyOverrides({
                            "OvfEy1I7B-hover": {
                                "data-framer-name": undefined
                            },
                            "Xopd_EfEJ-hover": {
                                "data-framer-name": undefined
                            },
                            OvfEy1I7B: {
                                "data-framer-name": "Inverse"
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(Transition, {
                            value: transition2,
                            children: /*#__PURE__*/ _jsxs(motion.div, {
                                className: "framer-1nfv7aq",
                                "data-framer-name": "Inner",
                                layoutDependency: layoutDependency,
                                layoutId: "truhv4dqO",
                                children: [ /*#__PURE__*/ _jsx(RichText, {
                                    __fromCanvasComponent: true,
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            className: "framer-styles-preset-7t5tvx",
                                            "data-styles-preset": "AqofocsPm",
                                            style: {
                                                "--framer-text-alignment": "left",
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--token-797a2fb4-2d14-46eb-9fb6-f38c1a9a545e, rgba(14, 16, 17, 0.6)))"
                                            },
                                            children: "Item"
                                        })
                                    }),
                                    className: "framer-1tlw5a6",
                                    fonts: ["Inter"],
                                    layoutDependency: layoutDependency,
                                    layoutId: "sFDXhKbEk",
                                    style: {
                                        "--extracted-r6o4lv": "var(--token-797a2fb4-2d14-46eb-9fb6-f38c1a9a545e, rgba(14, 16, 17, 0.6))"
                                    },
                                    text: Q0n_gFqmK,
                                    variants: {
                                        "OvfEy1I7B-hover": {
                                            "--extracted-r6o4lv": "var(--token-c5446a54-80de-4f79-b24b-55997bf1fe5e, rgb(255, 255, 255))"
                                        },
                                        OvfEy1I7B: {
                                            "--extracted-r6o4lv": "var(--token-d65913ad-f961-467c-89e1-937264b2cda0, rgba(255, 255, 255, 0.6))"
                                        }
                                    },
                                    verticalAlignment: "top",
                                    withExternalLayout: true,
                                    ...addPropertyOverrides({
                                        "OvfEy1I7B-hover": {
                                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                                children: /*#__PURE__*/ _jsx(motion.p, {
                                                    className: "framer-styles-preset-7t5tvx",
                                                    "data-styles-preset": "AqofocsPm",
                                                    style: {
                                                        "--framer-text-alignment": "left",
                                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-c5446a54-80de-4f79-b24b-55997bf1fe5e, rgb(255, 255, 255)))"
                                                    },
                                                    children: "Item"
                                                })
                                            })
                                        },
                                        OvfEy1I7B: {
                                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                                children: /*#__PURE__*/ _jsx(motion.p, {
                                                    className: "framer-styles-preset-7t5tvx",
                                                    "data-styles-preset": "AqofocsPm",
                                                    style: {
                                                        "--framer-text-alignment": "left",
                                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-d65913ad-f961-467c-89e1-937264b2cda0, rgba(255, 255, 255, 0.6)))"
                                                    },
                                                    children: "Item"
                                                })
                                            })
                                        }
                                    }, baseVariant, gestureVariant)
                                }), /*#__PURE__*/ _jsx(RichText, {
                                    __fromCanvasComponent: true,
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            className: "framer-styles-preset-7t5tvx",
                                            "data-styles-preset": "AqofocsPm",
                                            style: {
                                                "--framer-text-alignment": "left",
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--token-797a2fb4-2d14-46eb-9fb6-f38c1a9a545e, rgba(14, 16, 17, 0.6)))"
                                            },
                                            children: "Item"
                                        })
                                    }),
                                    className: "framer-nvw17z",
                                    fonts: ["Inter"],
                                    layoutDependency: layoutDependency,
                                    layoutId: "I7_msZz1o",
                                    style: {
                                        "--extracted-r6o4lv": "var(--token-797a2fb4-2d14-46eb-9fb6-f38c1a9a545e, rgba(14, 16, 17, 0.6))"
                                    },
                                    text: Q0n_gFqmK,
                                    variants: {
                                        "OvfEy1I7B-hover": {
                                            "--extracted-r6o4lv": "var(--token-c5446a54-80de-4f79-b24b-55997bf1fe5e, rgb(255, 255, 255))"
                                        },
                                        "Xopd_EfEJ-hover": {
                                            "--extracted-r6o4lv": "var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, rgb(14, 16, 17))"
                                        },
                                        OvfEy1I7B: {
                                            "--extracted-r6o4lv": "var(--token-d65913ad-f961-467c-89e1-937264b2cda0, rgba(255, 255, 255, 0.6))"
                                        }
                                    },
                                    verticalAlignment: "top",
                                    withExternalLayout: true,
                                    ...addPropertyOverrides({
                                        "OvfEy1I7B-hover": {
                                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                                children: /*#__PURE__*/ _jsx(motion.p, {
                                                    className: "framer-styles-preset-7t5tvx",
                                                    "data-styles-preset": "AqofocsPm",
                                                    style: {
                                                        "--framer-text-alignment": "left",
                                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-c5446a54-80de-4f79-b24b-55997bf1fe5e, rgb(255, 255, 255)))"
                                                    },
                                                    children: "Item"
                                                })
                                            })
                                        },
                                        "Xopd_EfEJ-hover": {
                                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                                children: /*#__PURE__*/ _jsx(motion.p, {
                                                    className: "framer-styles-preset-7t5tvx",
                                                    "data-styles-preset": "AqofocsPm",
                                                    style: {
                                                        "--framer-text-alignment": "left",
                                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, rgb(14, 16, 17)))"
                                                    },
                                                    children: "Item"
                                                })
                                            })
                                        },
                                        OvfEy1I7B: {
                                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                                children: /*#__PURE__*/ _jsx(motion.p, {
                                                    className: "framer-styles-preset-7t5tvx",
                                                    "data-styles-preset": "AqofocsPm",
                                                    style: {
                                                        "--framer-text-alignment": "left",
                                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-d65913ad-f961-467c-89e1-937264b2cda0, rgba(255, 255, 255, 0.6)))"
                                                    },
                                                    children: "Item"
                                                })
                                            })
                                        }
                                    }, baseVariant, gestureVariant)
                                })]
                            })
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-5VmjC.framer-1l20qc7, .framer-5VmjC .framer-1l20qc7 { display: block; }", ".framer-5VmjC.framer-1m42knt { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }", ".framer-5VmjC .framer-1nfv7aq { align-content: center; align-items: center; align-self: stretch; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 1px; height: 21px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: auto; }", ".framer-5VmjC .framer-1tlw5a6, .framer-5VmjC .framer-nvw17z { flex: none; height: auto; overflow: visible; position: relative; white-space: pre; width: auto; }", ".framer-5VmjC.framer-v-1m42knt.hover .framer-1nfv7aq, .framer-5VmjC.framer-v-qxphcx.hover .framer-1nfv7aq { justify-content: flex-end; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 21
 * @framerIntrinsicWidth 33
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"OvfEy1I7B":{"layout":["auto","auto"]},"FpuIehZzJ":{"layout":["auto","auto"]},"nxD4aCNpr":{"layout":["auto","auto"]}}}
 * @framerVariables {"Q0n_gFqmK":"title","NTOnIbDOf":"link","JzvcOuD__":"newTab","GY5rHEk7n":"smoothScroll","oTGribf8Y":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerFWoRjh02q = withCSS(Component, css, "framer-5VmjC");
export default FramerFWoRjh02q;
FramerFWoRjh02q.displayName = "Components/Nav Item";
FramerFWoRjh02q.defaultProps = {
    height: 21,
    width: 33
};
addPropertyControls(FramerFWoRjh02q, {
    variant: {
        options: ["Xopd_EfEJ", "OvfEy1I7B"],
        optionTitles: ["Default", "Inverse"],
        title: "Variant",
        type: ControlType.Enum
    },
    Q0n_gFqmK: {
        defaultValue: "Item",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    NTOnIbDOf: {
        title: "Link",
        type: ControlType.Link
    },
    JzvcOuD__: {
        defaultValue: false,
        title: "New Tab",
        type: ControlType.Boolean
    },
    GY5rHEk7n: {
        defaultValue: false,
        title: "Smooth Scroll",
        type: ControlType.Boolean
    },
    oTGribf8Y: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(FramerFWoRjh02q, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerFWoRjh02q",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerImmutableVariables": "true",
                "framerColorSyntax": "true",
                "framerIntrinsicHeight": "21",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"OvfEy1I7B\":{\"layout\":[\"auto\",\"auto\"]},\"FpuIehZzJ\":{\"layout\":[\"auto\",\"auto\"]},\"nxD4aCNpr\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerIntrinsicWidth": "33",
                "framerComponentViewportWidth": "true",
                "framerVariables": "{\"Q0n_gFqmK\":\"title\",\"NTOnIbDOf\":\"link\",\"JzvcOuD__\":\"newTab\",\"GY5rHEk7n\":\"smoothScroll\",\"oTGribf8Y\":\"click\"}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./FWoRjh02q.map