// Generated by Framer (5b26096)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    Link,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/5q66Fb7vwXwYqaHrBnM0/2QflXUmWkrUhgmkpzZQL/bgfpiv_eO.js";
const serializationHash = "framer-eU4IC";
const variantClassNames = {
    OS092PJcL: "framer-v-1jd0c3k"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    click,
    height,
    id,
    link,
    newTab,
    title,
    width,
    ...props
}) => {
    return { ...props,
        CYww2fMyc: title ? ? props.CYww2fMyc ? ? "Title",
        hhTmPuF4a: newTab ? ? props.hhTmPuF4a,
        HXKsYYAlQ: link ? ? props.HXKsYYAlQ,
        i6WSxl55l: click ? ? props.i6WSxl55l
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        CYww2fMyc,
        HXKsYYAlQ,
        hhTmPuF4a,
        i6WSxl55l,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "OS092PJcL",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTapnrc5nn = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (i6WSxl55l) {
            const res = await i6WSxl55l(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: HXKsYYAlQ,
                    motionChild: true,
                    nodeId: "OS092PJcL",
                    openInNewTab: hhTmPuF4a,
                    scopeId: "sUskDLZ5q",
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-1jd0c3k",className,classNames)} framer-19u72vy`,
                        "data-framer-name": "Default",
                        "data-highlight": true,
                        layoutDependency: layoutDependency,
                        layoutId: "OS092PJcL",
                        onTap: onTapnrc5nn,
                        ref: refBinding,
                        style: {
                            backgroundColor: "var(--token-4321a524-8651-4268-85f9-e884d8cb6223, rgb(255, 255, 255))",
                            ...style
                        },
                        children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-1129spx",
                                    "data-styles-preset": "bgfpiv_eO",
                                    children: "Title"
                                })
                            }),
                            className: "framer-pdux74",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "trZwSLLUn",
                            style: {
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: CYww2fMyc,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-eU4IC.framer-19u72vy, .framer-eU4IC .framer-19u72vy { display: block; }", ".framer-eU4IC.framer-1jd0c3k { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 10px 0px 10px 0px; position: relative; text-decoration: none; width: 200px; }", ".framer-eU4IC .framer-pdux74 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 39
 * @framerIntrinsicWidth 200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"CYww2fMyc":"title","HXKsYYAlQ":"link","hhTmPuF4a":"newTab","i6WSxl55l":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramersUskDLZ5q = withCSS(Component, css, "framer-eU4IC");
export default FramersUskDLZ5q;
FramersUskDLZ5q.displayName = "Mobile Menu Subnav Item";
FramersUskDLZ5q.defaultProps = {
    height: 39,
    width: 200
};
addPropertyControls(FramersUskDLZ5q, {
    CYww2fMyc: {
        defaultValue: "Title",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    HXKsYYAlQ: {
        title: "Link",
        type: ControlType.Link
    },
    hhTmPuF4a: {
        defaultValue: false,
        title: "New Tab",
        type: ControlType.Boolean
    },
    i6WSxl55l: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(FramersUskDLZ5q, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramersUskDLZ5q",
            "slots": [],
            "annotations": {
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true",
                "framerVariables": "{\"CYww2fMyc\":\"title\",\"HXKsYYAlQ\":\"link\",\"hhTmPuF4a\":\"newTab\",\"i6WSxl55l\":\"click\"}",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "200",
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicHeight": "39",
                "framerDisplayContentsDiv": "false"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./sUskDLZ5q.map