// Generated by Framer (dc53115)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import FC_GlobalCountryFlags from "https://framerusercontent.com/modules/6DL2PESnBGZ4TTphi6gj/AtrKpjqaFZPe5vcWWzpR/FC_GlobalCountryFlags.js";
const FC_GlobalCountryFlagsFonts = getFonts(FC_GlobalCountryFlags);
const enabledGestures = {
    XYgkzrDNv: {
        hover: true
    }
};
const serializationHash = "framer-w4dEL";
const variantClassNames = {
    XYgkzrDNv: "framer-v-1vnpsrh"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    click,
    height,
    hover,
    id,
    width,
    ...props
}) => {
    return { ...props,
        DotSQAtOa: hover ? ? props.DotSQAtOa,
        zH1LziHVm: click ? ? props.zH1LziHVm
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        DotSQAtOa,
        zH1LziHVm,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "XYgkzrDNv",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap5tcueg = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (zH1LziHVm) {
            const res = await zH1LziHVm(...args);
            if (res === false) return false;
        }
    });
    const onMouseEnter1a5d2tr = activeVariantCallback(async (...args) => {
        setGestureState({
            isHovered: true
        });
        if (DotSQAtOa) {
            const res = await DotSQAtOa(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1vnpsrh", className, classNames),
                    "data-framer-name": "Default",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "XYgkzrDNv",
                    onMouseEnter: onMouseEnter1a5d2tr,
                    onTap: onTap5tcueg,
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-4321a524-8651-4268-85f9-e884d8cb6223, rgb(255, 255, 255))",
                        ...style
                    },
                    ...addPropertyOverrides({
                        "XYgkzrDNv-hover": {
                            "data-framer-name": undefined
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-ii6vy8-container",
                            isAuthoredByUser: true,
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "IQCL3iaVQ-container",
                            nodeId: "IQCL3iaVQ",
                            rendersWithMotion: true,
                            scopeId: "drGNziehm",
                            style: {
                                scale: 1
                            },
                            variants: {
                                "XYgkzrDNv-hover": {
                                    scale: .9
                                }
                            },
                            children: /*#__PURE__*/ _jsx(FC_GlobalCountryFlags, {
                                canvas: "US",
                                country: "US",
                                height: "100%",
                                id: "IQCL3iaVQ",
                                isSquare: false,
                                layoutId: "IQCL3iaVQ",
                                radius: 2,
                                style: {
                                    width: "100%"
                                },
                                useActive: true,
                                width: "100%"
                            })
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-w4dEL.framer-u2267, .framer-w4dEL .framer-u2267 { display: block; }", ".framer-w4dEL.framer-1vnpsrh { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: 32px; justify-content: center; overflow: visible; padding: 6px; position: relative; width: min-content; }", ".framer-w4dEL .framer-ii6vy8-container { flex: none; height: auto; position: relative; width: 16px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 32
 * @framerIntrinsicWidth 28
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"cdu8Gg1Pq":{"layout":["auto","fixed"]}}}
 * @framerVariables {"DotSQAtOa":"hover","zH1LziHVm":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerdrGNziehm = withCSS(Component, css, "framer-w4dEL");
export default FramerdrGNziehm;
FramerdrGNziehm.displayName = "Markets Toggle";
FramerdrGNziehm.defaultProps = {
    height: 32,
    width: 28
};
addPropertyControls(FramerdrGNziehm, {
    DotSQAtOa: {
        title: "Hover",
        type: ControlType.EventHandler
    },
    zH1LziHVm: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(FramerdrGNziehm, [{
    explicitInter: true,
    fonts: []
}, ...FC_GlobalCountryFlagsFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerdrGNziehm",
            "slots": [],
            "annotations": {
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerAutoSizeImages": "true",
                "framerVariables": "{\"DotSQAtOa\":\"hover\",\"zH1LziHVm\":\"click\"}",
                "framerIntrinsicHeight": "32",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"fixed\"]},\"cdu8Gg1Pq\":{\"layout\":[\"auto\",\"fixed\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "28",
                "framerComponentViewportWidth": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./drGNziehm.map