// Generated by Framer (dc53115)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useOnVariantChange,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["vCCTyCCMx", "nldeyZ9u9", "L57dI5FDF"];
const serializationHash = "framer-NO9S3";
const variantClassNames = {
    L57dI5FDF: "framer-v-1yci7hp",
    nldeyZ9u9: "framer-v-38j1yl",
    vCCTyCCMx: "framer-v-18mbrsc"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 60,
    delay: 0,
    mass: 1,
    stiffness: 500,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Close: "L57dI5FDF",
    Default: "vCCTyCCMx",
    Transition: "nldeyZ9u9"
};
const getProps = ({
    height,
    id,
    tap,
    width,
    ...props
}) => {
    return { ...props,
        sJ3RhKUYy: tap ? ? props.sJ3RhKUYy,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "vCCTyCCMx"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        sJ3RhKUYy,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "vCCTyCCMx",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap1xwg1rq = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (sJ3RhKUYy) {
            const res = await sJ3RhKUYy(...args);
            if (res === false) return false;
        }
        setVariant("nldeyZ9u9");
    });
    const onAppearf6qym9 = activeVariantCallback(async (...args) => {
        await delay(() => setVariant("L57dI5FDF"), 200);
    });
    const onTapoa5mt4 = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (sJ3RhKUYy) {
            const res = await sJ3RhKUYy(...args);
            if (res === false) return false;
        }
        setVariant("vCCTyCCMx");
    });
    useOnVariantChange(baseVariant, {
        nldeyZ9u9: onAppearf6qym9
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-18mbrsc", className, classNames),
                    "data-framer-name": "Default",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "vCCTyCCMx",
                    onTap: onTap1xwg1rq,
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-5087bb56-e67b-4acc-afc9-0cb2e336d0c2, rgb(242, 242, 239))",
                        borderBottomLeftRadius: 6,
                        borderBottomRightRadius: 6,
                        borderTopLeftRadius: 6,
                        borderTopRightRadius: 6,
                        ...style
                    },
                    ...addPropertyOverrides({
                        L57dI5FDF: {
                            "data-framer-name": "Close",
                            onTap: onTapoa5mt4
                        },
                        nldeyZ9u9: {
                            "data-framer-name": "Transition"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-awly5t",
                        "data-framer-name": "Line",
                        layoutDependency: layoutDependency,
                        layoutId: "JMZLTSkmY",
                        style: {
                            backgroundColor: "var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, rgb(26, 28, 24))",
                            rotate: 0
                        },
                        variants: {
                            L57dI5FDF: {
                                rotate: 45
                            }
                        }
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1xb4932",
                        "data-framer-name": "Line",
                        layoutDependency: layoutDependency,
                        layoutId: "phKI8GGE7",
                        style: {
                            backgroundColor: "var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, rgb(26, 28, 24))",
                            rotate: 0
                        },
                        variants: {
                            L57dI5FDF: {
                                rotate: -45
                            }
                        }
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-NO9S3.framer-w6r9pq, .framer-NO9S3 .framer-w6r9pq { display: block; }", ".framer-NO9S3.framer-18mbrsc { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 34px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 34px; will-change: var(--framer-will-change-override, transform); }", ".framer-NO9S3 .framer-awly5t { flex: none; height: 1px; left: calc(50.00000000000002% - 16px / 2); overflow: visible; position: absolute; top: 13px; width: 16px; z-index: 1; }", ".framer-NO9S3 .framer-1xb4932 { bottom: 13px; flex: none; height: 1px; left: calc(50.00000000000002% - 16px / 2); overflow: visible; position: absolute; width: 16px; z-index: 1; }", ".framer-NO9S3.framer-v-38j1yl .framer-awly5t, .framer-NO9S3.framer-v-1yci7hp .framer-awly5t { top: calc(50.00000000000002% - 1px / 2); }", ".framer-NO9S3.framer-v-38j1yl .framer-1xb4932, .framer-NO9S3.framer-v-1yci7hp .framer-1xb4932 { bottom: unset; top: calc(50.00000000000002% - 1px / 2); }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 34
 * @framerIntrinsicWidth 34
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"nldeyZ9u9":{"layout":["fixed","fixed"]},"L57dI5FDF":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"sJ3RhKUYy":"tap"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerYdTNrqO1f = withCSS(Component, css, "framer-NO9S3");
export default FramerYdTNrqO1f;
FramerYdTNrqO1f.displayName = "Mobile Menu Toggle";
FramerYdTNrqO1f.defaultProps = {
    height: 34,
    width: 34
};
addPropertyControls(FramerYdTNrqO1f, {
    variant: {
        options: ["vCCTyCCMx", "nldeyZ9u9", "L57dI5FDF"],
        optionTitles: ["Default", "Transition", "Close"],
        title: "Variant",
        type: ControlType.Enum
    },
    sJ3RhKUYy: {
        title: "Tap",
        type: ControlType.EventHandler
    }
});
addFonts(FramerYdTNrqO1f, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerYdTNrqO1f",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "34",
                "framerImmutableVariables": "true",
                "framerVariables": "{\"sJ3RhKUYy\":\"tap\"}",
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"nldeyZ9u9\":{\"layout\":[\"fixed\",\"fixed\"]},\"L57dI5FDF\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerColorSyntax": "true",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerIntrinsicHeight": "34"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./YdTNrqO1f.map