// Generated by Framer (c07a8c1)
import {
    fontStore
} from "framer";
fontStore.loadFonts(["GF;Figtree-regular", "GF;Figtree-700", "GF;Figtree-700italic", "GF;Figtree-italic"]);
export const fonts = [{
    explicitInter: true,
    fonts: [{
        family: "Figtree",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/figtree/v7/_Xmz-HUzqDCFdgfMsYiV_F7wfS-Bs_d_QF5bwkEU4HTy.woff2",
        weight: "400"
    }, {
        family: "Figtree",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/figtree/v7/_Xmz-HUzqDCFdgfMsYiV_F7wfS-Bs_eYR15bwkEU4HTy.woff2",
        weight: "700"
    }, {
        family: "Figtree",
        source: "google",
        style: "italic",
        url: "https://fonts.gstatic.com/s/figtree/v7/_Xm9-HUzqDCFdgfMm4GnA4aZFrUvtOK3A1EayEA25WTybO8.woff2",
        weight: "700"
    }, {
        family: "Figtree",
        source: "google",
        style: "italic",
        url: "https://fonts.gstatic.com/s/figtree/v7/_Xm9-HUzqDCFdgfMm4GnA4aZFrUvtOK3A7YdyEA25WTybO8.woff2",
        weight: "400"
    }]
}];
export const css = ['.framer-HdVzQ .framer-styles-preset-swuwne:not(.rich-text-wrapper), .framer-HdVzQ .framer-styles-preset-swuwne.rich-text-wrapper p { --framer-font-family: "Figtree", "Figtree Placeholder", sans-serif; --framer-font-family-bold: "Figtree", "Figtree Placeholder", sans-serif; --framer-font-family-bold-italic: "Figtree", "Figtree Placeholder", sans-serif; --framer-font-family-italic: "Figtree", "Figtree Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0px; --framer-line-height: 120%; --framer-paragraph-spacing: 0px; --framer-text-alignment: left; --framer-text-color: var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, #dac5a7); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }'];
export const className = "framer-HdVzQ";
export const __FramerMetadata__ = {
    "exports": {
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}