// Generated by Framer (dc53115)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS,
    withFX
} from "framer";
import {
    LayoutGroup,
    motion
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/e6hu5bFF0rCCT36GTgql/7w2AGuc6YvnRZqrREkKN/jeIIip8Yb.js";
const MotionDivWithFX = withFX(motion.div);
const enabledGestures = {
    FRVd_VXvb: {
        hover: true,
        pressed: true
    }
};
const cycleOrder = ["FRVd_VXvb", "wlRQztzSQ", "N31tV4Bgv", "xmg9YfNF9", "covBNY0Qx"];
const serializationHash = "framer-v7bvD";
const variantClassNames = {
    covBNY0Qx: "framer-v-16l0cbx",
    FRVd_VXvb: "framer-v-rds3ev",
    N31tV4Bgv: "framer-v-l3vuug",
    wlRQztzSQ: "framer-v-1jcnnaq",
    xmg9YfNF9: "framer-v-1ga8u56"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    delay: 0,
    duration: 1,
    ease: [0, 0, 1, 1],
    type: "tween"
};
const animation = {
    opacity: 1,
    rotate: 360,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 0
};
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Default: "FRVd_VXvb",
    Disabled: "N31tV4Bgv",
    Error: "covBNY0Qx",
    Loading: "wlRQztzSQ",
    Success: "xmg9YfNF9"
};
const getProps = ({
    height,
    id,
    title,
    width,
    ...props
}) => {
    return { ...props,
        m0q7lVsF5: title ? ? props.m0q7lVsF5 ? ? "Subscribe",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "FRVd_VXvb"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        m0q7lVsF5,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "FRVd_VXvb",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (baseVariant === "wlRQztzSQ") return false;
        return true;
    };
    const isDisplayed1 = () => {
        if (baseVariant === "wlRQztzSQ") return true;
        return false;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsxs(motion.button, { ...restProps,
                ...gestureHandlers,
                className: cx(scopingClassNames, "framer-rds3ev", className, classNames),
                "data-framer-name": "Default",
                "data-reset": "button",
                layoutDependency: layoutDependency,
                layoutId: "FRVd_VXvb",
                ref: refBinding,
                style: {
                    backgroundColor: "var(--token-b33ee92c-1ff7-4447-97d0-592480c21cbc, rgb(117, 125, 92))",
                    borderBottomLeftRadius: 500,
                    borderBottomRightRadius: 500,
                    borderTopLeftRadius: 500,
                    borderTopRightRadius: 500,
                    opacity: 1,
                    ...style
                },
                variants: {
                    "FRVd_VXvb-hover": {
                        opacity: 1
                    },
                    "FRVd_VXvb-pressed": {
                        opacity: 1
                    },
                    covBNY0Qx: {
                        backgroundColor: "rgba(255, 34, 68, 0.15)",
                        opacity: 1
                    },
                    N31tV4Bgv: {
                        opacity: .5
                    },
                    xmg9YfNF9: {
                        opacity: 1
                    }
                },
                ...addPropertyOverrides({
                    "FRVd_VXvb-hover": {
                        "data-framer-name": undefined
                    },
                    "FRVd_VXvb-pressed": {
                        "data-framer-name": undefined
                    },
                    covBNY0Qx: {
                        "data-framer-name": "Error"
                    },
                    N31tV4Bgv: {
                        "data-framer-name": "Disabled"
                    },
                    wlRQztzSQ: {
                        "data-framer-name": "Loading"
                    },
                    xmg9YfNF9: {
                        "data-framer-name": "Success"
                    }
                }, baseVariant, gestureVariant),
                children: [isDisplayed() && /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-swuwne",
                            "data-styles-preset": "jeIIip8Yb",
                            style: {
                                "--framer-text-color": "var(--extracted-r6o4lv, var(--token-c5446a54-80de-4f79-b24b-55997bf1fe5e, rgb(255, 255, 255)))"
                            },
                            children: "Subscribe"
                        })
                    }),
                    className: "framer-il9pok",
                    fonts: ["Inter"],
                    layoutDependency: layoutDependency,
                    layoutId: "V7fvT61lC",
                    style: {
                        "--extracted-r6o4lv": "var(--token-c5446a54-80de-4f79-b24b-55997bf1fe5e, rgb(255, 255, 255))",
                        "--framer-link-text-color": "rgb(0, 153, 255)",
                        "--framer-link-text-decoration": "underline"
                    },
                    text: m0q7lVsF5,
                    variants: {
                        covBNY0Qx: {
                            "--extracted-r6o4lv": "rgb(255, 34, 68)"
                        },
                        xmg9YfNF9: {
                            "--extracted-r6o4lv": "rgb(255, 255, 255)"
                        }
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides({
                        covBNY0Qx: {
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                                        "--framer-font-family": '"Inter", "Inter Placeholder", sans-serif',
                                        "--framer-font-size": "14px",
                                        "--framer-font-weight": "600",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 34, 68))"
                                    },
                                    children: "Something went wrong"
                                })
                            }),
                            fonts: ["Inter-SemiBold"],
                            text: undefined
                        },
                        xmg9YfNF9: {
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                                        "--framer-font-family": '"Inter", "Inter Placeholder", sans-serif',
                                        "--framer-font-size": "14px",
                                        "--framer-font-weight": "600",
                                        "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))"
                                    },
                                    children: "Thank you"
                                })
                            }),
                            fonts: ["Inter-SemiBold"],
                            text: undefined
                        }
                    }, baseVariant, gestureVariant)
                }), isDisplayed1() && /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-1efezfm",
                    "data-framer-name": "Spinner",
                    layoutDependency: layoutDependency,
                    layoutId: "lMwHdrC89",
                    style: {
                        mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
                        WebkitMask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add"
                    },
                    children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
                        __framer__loop: animation,
                        __framer__loopEffectEnabled: true,
                        __framer__loopRepeatDelay: 0,
                        __framer__loopRepeatType: "loop",
                        __framer__loopTransition: transition1,
                        __perspectiveFX: false,
                        __smartComponentFX: true,
                        __targetOpacity: 1,
                        className: "framer-1wrqzx6",
                        "data-framer-name": "Conic",
                        layoutDependency: layoutDependency,
                        layoutId: "M4n4KRFQg",
                        style: {
                            background: "conic-gradient(from 180deg at 50% 50%, rgb(68, 204, 255) 0deg, rgb(68, 204, 255) 360deg)",
                            backgroundColor: "rgb(68, 204, 255)",
                            mask: "none",
                            WebkitMask: "none"
                        },
                        variants: {
                            wlRQztzSQ: {
                                background: "conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
                                backgroundColor: "rgba(0, 0, 0, 0)",
                                mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
                                WebkitMask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add"
                            }
                        },
                        children: /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-1474mfy",
                            "data-framer-name": "Rounding",
                            layoutDependency: layoutDependency,
                            layoutId: "FEbKLNxxz",
                            style: {
                                backgroundColor: "rgb(255, 255, 255)",
                                borderBottomLeftRadius: 1,
                                borderBottomRightRadius: 1,
                                borderTopLeftRadius: 1,
                                borderTopRightRadius: 1
                            },
                            transformTemplate: transformTemplate1
                        })
                    })
                })]
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-v7bvD.framer-1wde6sz, .framer-v7bvD .framer-1wde6sz { display: block; }", ".framer-v7bvD.framer-rds3ev { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 12px 20px 12px 20px; position: relative; width: min-content; }", ".framer-v7bvD .framer-il9pok { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }", ".framer-v7bvD .framer-1efezfm { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }", ".framer-v7bvD .framer-1wrqzx6 { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }", ".framer-v7bvD .framer-1474mfy { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }", ".framer-v7bvD.framer-v-1jcnnaq.framer-rds3ev, .framer-v7bvD.framer-v-l3vuug.framer-rds3ev, .framer-v7bvD.framer-v-1ga8u56.framer-rds3ev, .framer-v7bvD.framer-v-16l0cbx.framer-rds3ev { cursor: unset; }", ".framer-v7bvD.framer-v-1jcnnaq .framer-1wrqzx6 { overflow: hidden; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 43
 * @framerIntrinsicWidth 111.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"wlRQztzSQ":{"layout":["auto","auto"]},"N31tV4Bgv":{"layout":["auto","auto"]},"xmg9YfNF9":{"layout":["auto","auto"]},"covBNY0Qx":{"layout":["auto","auto"]},"Yd53DfQ5C":{"layout":["auto","auto"]},"gvbFajD7d":{"layout":["auto","auto"]}}}
 * @framerVariables {"m0q7lVsF5":"title"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerK4iMa3lm1 = withCSS(Component, css, "framer-v7bvD");
export default FramerK4iMa3lm1;
FramerK4iMa3lm1.displayName = "Section Newsletter Form Button";
FramerK4iMa3lm1.defaultProps = {
    height: 43,
    width: 111.5
};
addPropertyControls(FramerK4iMa3lm1, {
    variant: {
        options: ["FRVd_VXvb", "wlRQztzSQ", "N31tV4Bgv", "xmg9YfNF9", "covBNY0Qx"],
        optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
        title: "Variant",
        type: ControlType.Enum
    },
    m0q7lVsF5: {
        defaultValue: "Subscribe",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    }
});
addFonts(FramerK4iMa3lm1, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
        weight: "600"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
        weight: "600"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
        weight: "600"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
        weight: "600"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
        weight: "600"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/1ZFS7N918ojhhd0nQWdj3jz4w.woff2",
        weight: "600"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
        weight: "600"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerK4iMa3lm1",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "43",
                "framerVariables": "{\"m0q7lVsF5\":\"title\"}",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicWidth": "111.5",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"wlRQztzSQ\":{\"layout\":[\"auto\",\"auto\"]},\"N31tV4Bgv\":{\"layout\":[\"auto\",\"auto\"]},\"xmg9YfNF9\":{\"layout\":[\"auto\",\"auto\"]},\"covBNY0Qx\":{\"layout\":[\"auto\",\"auto\"]},\"Yd53DfQ5C\":{\"layout\":[\"auto\",\"auto\"]},\"gvbFajD7d\":{\"layout\":[\"auto\",\"auto\"]}}}"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./K4iMa3lm1.map