// Generated by Framer (0320f5c)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getLoadingLazyAtYPosition,
    Image,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const enabledGestures = {
    mPlFdlxWU: {
        hover: true
    },
    pCJyQ0rUz: {
        hover: true
    }
};
const cycleOrder = ["pCJyQ0rUz", "mPlFdlxWU", "GnEtkTFqk"];
const serializationHash = "framer-M6qgY";
const variantClassNames = {
    GnEtkTFqk: "framer-v-ta5fs0",
    mPlFdlxWU: "framer-v-1qf9nd",
    pCJyQ0rUz: "framer-v-4q6g85"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const toResponsiveImage = value => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    }
    return typeof value === "string" ? {
        src: value
    } : undefined;
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "pCJyQ0rUz",
    Phone: "GnEtkTFqk",
    Tablet: "mPlFdlxWU"
};
const getProps = ({
    height,
    id,
    image,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "pCJyQ0rUz",
        Xw0BkQ43r: image ? ? props.Xw0BkQ43r
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        Xw0BkQ43r,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "pCJyQ0rUz",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-4q6g85", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "pCJyQ0rUz",
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-4321a524-8651-4268-85f9-e884d8cb6223, rgb(255, 255, 255))",
                        borderBottomLeftRadius: 8,
                        borderBottomRightRadius: 8,
                        borderTopLeftRadius: 8,
                        borderTopRightRadius: 8,
                        ...style
                    },
                    ...addPropertyOverrides({
                        "mPlFdlxWU-hover": {
                            "data-framer-name": undefined
                        },
                        "pCJyQ0rUz-hover": {
                            "data-framer-name": undefined
                        },
                        GnEtkTFqk: {
                            "data-framer-name": "Phone"
                        },
                        mPlFdlxWU: {
                            "data-framer-name": "Tablet"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(Transition, {
                        value: transition1,
                        children: /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-jfsjjb",
                            "data-framer-name": "Inner",
                            layoutDependency: layoutDependency,
                            layoutId: "lkJtn8or0",
                            style: {
                                backgroundColor: "var(--token-4321a524-8651-4268-85f9-e884d8cb6223, rgb(255, 255, 255))",
                                borderBottomLeftRadius: 8,
                                borderBottomRightRadius: 8,
                                borderTopLeftRadius: 8,
                                borderTopRightRadius: 8,
                                scale: 1
                            },
                            variants: {
                                "mPlFdlxWU-hover": {
                                    scale: 1.1
                                },
                                "pCJyQ0rUz-hover": {
                                    scale: 1.1
                                }
                            },
                            children: /*#__PURE__*/ _jsx(Image, {
                                background: {
                                    alt: "",
                                    fit: "fill",
                                    loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 70) - 0 - ((componentViewport ? .height || 70) - 0) * 1) / 2) + (5 + (((componentViewport ? .height || 70) - 0) * 1 - 10 - (((componentViewport ? .height || 70) - 0) * 1 - 10) * 1) / 2)),
                                    sizes: `max(max(${componentViewport?.width||"100vw"}, 1px) - 10px, 1px)`,
                                    ...toResponsiveImage(Xw0BkQ43r)
                                },
                                className: "framer-9jflgr",
                                "data-framer-name": "Image",
                                layoutDependency: layoutDependency,
                                layoutId: "yufnq8LuR",
                                style: {
                                    borderBottomLeftRadius: 6,
                                    borderBottomRightRadius: 6,
                                    borderTopLeftRadius: 6,
                                    borderTopRightRadius: 6
                                },
                                ...addPropertyOverrides({
                                    GnEtkTFqk: {
                                        background: {
                                            alt: "",
                                            fit: "fill",
                                            loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 60) - 0 - ((componentViewport ? .height || 60) - 0) * 1) / 2) + (3 + (((componentViewport ? .height || 60) - 0) * 1 - 6 - (((componentViewport ? .height || 60) - 0) * 1 - 6) * 1) / 2)),
                                            sizes: `max(max(${componentViewport?.width||"100vw"}, 1px) - 6px, 1px)`,
                                            ...toResponsiveImage(Xw0BkQ43r)
                                        }
                                    },
                                    mPlFdlxWU: {
                                        background: {
                                            alt: "",
                                            fit: "fill",
                                            loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 65) - 0 - ((componentViewport ? .height || 65) - 0) * 1) / 2) + (4 + (((componentViewport ? .height || 65) - 0) * 1 - 8 - (((componentViewport ? .height || 65) - 0) * 1 - 8) * 1) / 2)),
                                            sizes: `max(max(${componentViewport?.width||"100vw"}, 1px) - 8px, 1px)`,
                                            ...toResponsiveImage(Xw0BkQ43r)
                                        }
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-M6qgY.framer-10qcn8, .framer-M6qgY .framer-10qcn8 { display: block; }", ".framer-M6qgY.framer-4q6g85 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 70px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 70px; }", ".framer-M6qgY .framer-jfsjjb { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: flex-start; overflow: hidden; padding: 5px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }", ".framer-M6qgY .framer-9jflgr { flex: 1 0 0px; gap: 0px; height: 100%; overflow: hidden; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }", ".framer-M6qgY.framer-v-1qf9nd.framer-4q6g85 { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 65px); width: 65px; }", ".framer-M6qgY.framer-v-1qf9nd .framer-jfsjjb { padding: 4px; }", ".framer-M6qgY.framer-v-ta5fs0.framer-4q6g85 { aspect-ratio: 1 / 1; cursor: unset; height: var(--framer-aspect-ratio-supported, 60px); width: 60px; }", ".framer-M6qgY.framer-v-ta5fs0 .framer-jfsjjb { padding: 3px; }", ".framer-M6qgY.framer-v-4q6g85.hover.framer-4q6g85 { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 70px); }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 70
 * @framerIntrinsicWidth 70
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"mPlFdlxWU":{"layout":["fixed","fixed"]},"GnEtkTFqk":{"layout":["fixed","fixed"]},"xJ5hdr3rQ":{"layout":["fixed","fixed"]},"lMtfCJmAr":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"Xw0BkQ43r":"image"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerVQ0IaOcV9 = withCSS(Component, css, "framer-M6qgY");
export default FramerVQ0IaOcV9;
FramerVQ0IaOcV9.displayName = "Image Small";
FramerVQ0IaOcV9.defaultProps = {
    height: 70,
    width: 70
};
addPropertyControls(FramerVQ0IaOcV9, {
    variant: {
        options: ["pCJyQ0rUz", "mPlFdlxWU", "GnEtkTFqk"],
        optionTitles: ["Desktop", "Tablet", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    Xw0BkQ43r: {
        title: "Image",
        type: ControlType.ResponsiveImage
    }
});
addFonts(FramerVQ0IaOcV9, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerVQ0IaOcV9",
            "slots": [],
            "annotations": {
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"mPlFdlxWU\":{\"layout\":[\"fixed\",\"fixed\"]},\"GnEtkTFqk\":{\"layout\":[\"fixed\",\"fixed\"]},\"xJ5hdr3rQ\":{\"layout\":[\"fixed\",\"fixed\"]},\"lMtfCJmAr\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerIntrinsicWidth": "70",
                "framerDisplayContentsDiv": "false",
                "framerContractVersion": "1",
                "framerVariables": "{\"Xw0BkQ43r\":\"image\"}",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "70",
                "framerAutoSizeImages": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./VQ0IaOcV9.map