// Generated by Framer (14b65b1)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import FC_CartCounter from "https://framerusercontent.com/modules/4gxKhYDXhQYsHYSbypZW/CwQMBB6veGtRJ77hGsnc/FC_CartCounter.js";
import Icon from "https://framerusercontent.com/modules/IAD6uNsOXrmw3gEJy55n/ox2dPmfX2JipCh6x7f9F/yhTqxHqjh.js";
import FC_CartOverlayTrigger from "https://framerusercontent.com/modules/yA7N9WhjPTgbsU6xpomV/y7a0GEgWVtkVtKRFnvNa/FC_CartOverlayTrigger.js";
import HeaderIcons from "https://framerusercontent.com/modules/MeC7Qd2qToIpL7zjbWy7/QufMAXVWCLiYt6ZCxHZO/MImBaXi5t.js";
const FC_CartOverlayTriggerFonts = getFonts(FC_CartOverlayTrigger);
const FC_CartCounterFonts = getFonts(FC_CartCounter);
const HeaderIconsFonts = getFonts(HeaderIcons);
const serializationHash = "framer-zIJig";
const variantClassNames = {
    Z3hZ94VJx: "framer-v-v7h70n"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    click,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        a1bnx894r: click ? ? props.a1bnx894r
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        a1bnx894r,
        K0Hp2jTsB,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "Z3hZ94VJx",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTappgnr37 = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (a1bnx894r) {
            const res = await a1bnx894r(...args);
            if (res === false) return false;
        }
    });
    const triggerShopifyCartModalosbfku = activeVariantCallback(async (...args) => {
        if (a1bnx894r) {
            const res = await a1bnx894r(...args);
            if (res === false) return false;
        }
    });
    const O9okE1aeB10rkze7 = activeVariantCallback(async (...args) => {
        if (K0Hp2jTsB) {
            const res = await K0Hp2jTsB(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-v7h70n", className, classNames),
                    "data-framer-name": "Default",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "Z3hZ94VJx",
                    onTap: onTappgnr37,
                    ref: refBinding,
                    style: { ...style
                    },
                    children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-iabt3s-container",
                            isAuthoredByUser: true,
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "b75LGC7dP-container",
                            nodeId: "b75LGC7dP",
                            rendersWithMotion: true,
                            scopeId: "kbYuKBelK",
                            style: {
                                opacity: 0
                            },
                            children: /*#__PURE__*/ _jsx(FC_CartOverlayTrigger, {
                                height: "100%",
                                id: "b75LGC7dP",
                                layoutId: "b75LGC7dP",
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                triggerShopifyCartModal: triggerShopifyCartModalosbfku,
                                width: "100%"
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-15f19fv-container",
                            isAuthoredByUser: true,
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "vffVG0W_X-container",
                            nodeId: "vffVG0W_X",
                            rendersWithMotion: true,
                            scopeId: "kbYuKBelK",
                            children: /*#__PURE__*/ _jsx(FC_CartCounter, {
                                backgroundColor: "var(--token-dca875b7-f855-43c1-bf73-97596e452266, rgb(60, 68, 51))",
                                border: {
                                    borderColor: "rgb(0, 0, 0)",
                                    borderStyle: "solid",
                                    borderWidth: 0
                                },
                                bottomLeft: 500,
                                bottomRight: 500,
                                color: "var(--token-c5446a54-80de-4f79-b24b-55997bf1fe5e, rgb(255, 255, 255))",
                                font: {
                                    fontFamily: '"Figtree", "Figtree Placeholder", sans-serif',
                                    fontSize: "10px",
                                    fontStyle: "normal",
                                    fontWeight: 500,
                                    letterSpacing: "0em",
                                    lineHeight: "1em",
                                    textAlign: "center"
                                },
                                height: "100%",
                                hideIf0: true,
                                id: "vffVG0W_X",
                                layoutId: "vffVG0W_X",
                                padding: 5,
                                paddingBottom: 5,
                                paddingLeft: 8,
                                paddingPerSide: false,
                                paddingRight: 8,
                                paddingTop: 5,
                                radius: 500,
                                radiusPerCorner: false,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                topLeft: 500,
                                topRight: 500,
                                width: "100%"
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 32,
                        width: "32px",
                        y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 32) - 0 - 32) / 2),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1hh0poc-container",
                            layoutDependency: layoutDependency,
                            layoutId: "MJnOZyJvy-container",
                            nodeId: "MJnOZyJvy",
                            rendersWithMotion: true,
                            scopeId: "kbYuKBelK",
                            children: /*#__PURE__*/ _jsx(HeaderIcons, {
                                height: "100%",
                                id: "MJnOZyJvy",
                                IdUGFbNEq: Icon,
                                layoutId: "MJnOZyJvy",
                                O9okE1aeB: O9okE1aeB10rkze7,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                width: "100%"
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-zIJig.framer-ibbkln, .framer-zIJig .framer-ibbkln { display: block; }", ".framer-zIJig.framer-v7h70n { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-zIJig .framer-iabt3s-container { flex: none; height: 0%; left: calc(50.00000000000002% - 43.75% / 2); position: absolute; top: calc(50.00000000000002% - 0% / 2); width: 44%; z-index: 9; }", ".framer-zIJig .framer-15f19fv-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 16px); position: absolute; right: 0px; top: 0px; width: 16px; z-index: 1; }", ".framer-zIJig .framer-1hh0poc-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 32px); position: relative; width: 32px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 32
 * @framerIntrinsicWidth 32
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"a1bnx894r":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerkbYuKBelK = withCSS(Component, css, "framer-zIJig");
export default FramerkbYuKBelK;
FramerkbYuKBelK.displayName = "Cart Toggle";
FramerkbYuKBelK.defaultProps = {
    height: 32,
    width: 32
};
addPropertyControls(FramerkbYuKBelK, {
    a1bnx894r: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(FramerkbYuKBelK, [{
    explicitInter: true,
    fonts: [{
        family: "Figtree",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/figtree/v8/_Xmz-HUzqDCFdgfMsYiV_F7wfS-Bs_dNQF5bwkEU4HTy.woff2",
        weight: "500"
    }]
}, ...FC_CartOverlayTriggerFonts, ...FC_CartCounterFonts, ...HeaderIconsFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerkbYuKBelK",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "32",
                "framerVariables": "{\"a1bnx894r\":\"click\"}",
                "framerImmutableVariables": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "true",
                "framerIntrinsicHeight": "32",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./kbYuKBelK.map