// Generated by Framer (dc53115)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/e6hu5bFF0rCCT36GTgql/7w2AGuc6YvnRZqrREkKN/jeIIip8Yb.js";
const enabledGestures = {
    GUMBiD9Hi: {
        hover: true
    }
};
const serializationHash = "framer-w5bPZ";
const variantClassNames = {
    GUMBiD9Hi: "framer-v-ggjbbz"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 60,
    delay: 0,
    mass: 1,
    stiffness: 500,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "GUMBiD9Hi",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-ggjbbz", className, classNames),
                    "data-framer-name": "Button",
                    layoutDependency: layoutDependency,
                    layoutId: "GUMBiD9Hi",
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-dca875b7-f855-43c1-bf73-97596e452266, rgb(14, 16, 17))",
                        borderBottomLeftRadius: 500,
                        borderBottomRightRadius: 500,
                        borderTopLeftRadius: 500,
                        borderTopRightRadius: 500,
                        ...style
                    },
                    variants: {
                        "GUMBiD9Hi-hover": {
                            backgroundColor: "var(--token-b33ee92c-1ff7-4447-97d0-592480c21cbc, rgb(24, 27, 28))"
                        }
                    },
                    ...addPropertyOverrides({
                        "GUMBiD9Hi-hover": {
                            "data-framer-name": undefined
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-swuwne",
                                "data-styles-preset": "jeIIip8Yb",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-c5446a54-80de-4f79-b24b-55997bf1fe5e, rgb(255, 255, 255)))"
                                },
                                children: "Checkout"
                            })
                        }),
                        className: "framer-mnwijm",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "ZpK4Umvfp",
                        style: {
                            "--extracted-r6o4lv": "var(--token-c5446a54-80de-4f79-b24b-55997bf1fe5e, rgb(255, 255, 255))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-w5bPZ.framer-1td7v44, .framer-w5bPZ .framer-1td7v44 { display: block; }", ".framer-w5bPZ.framer-ggjbbz { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 44px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 300px; }", ".framer-w5bPZ .framer-mnwijm { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 44
 * @framerIntrinsicWidth 300
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"SnM0ZGnM_":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramertUIehpWcF = withCSS(Component, css, "framer-w5bPZ");
export default FramertUIehpWcF;
FramertUIehpWcF.displayName = "Cart Button";
FramertUIehpWcF.defaultProps = {
    height: 44,
    width: 300
};
addFonts(FramertUIehpWcF, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramertUIehpWcF",
            "slots": [],
            "annotations": {
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"SnM0ZGnM_\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicWidth": "300",
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerIntrinsicHeight": "44"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./tUIehpWcF.map