// Generated by Framer (34801f9)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    Link,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const enabledGestures = {
    FHNFMCMOj: {
        hover: true
    },
    Yp5vSngnR: {
        hover: true
    }
};
const cycleOrder = ["FHNFMCMOj", "Yp5vSngnR"];
const serializationHash = "framer-ohfFP";
const variantClassNames = {
    FHNFMCMOj: "framer-v-s36am5",
    Yp5vSngnR: "framer-v-5vx8oy"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const bF1RjQNm2 = undefined;
const tmJjEwoTa = undefined;
const zZgakqIy2 = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    Default: "FHNFMCMOj",
    Primary: "Yp5vSngnR"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    link,
    title,
    titleHover,
    width,
    ...props
}) => {
    return { ...props,
        bF1RjQNm2: link ? ? props.bF1RjQNm2,
        tmJjEwoTa: title ? ? props.tmJjEwoTa ? ? "Title",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "FHNFMCMOj",
        zZgakqIy2: titleHover ? ? props.zZgakqIy2 ? ? "Hover"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        tmJjEwoTa,
        zZgakqIy2,
        bF1RjQNm2,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "FHNFMCMOj",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: bF1RjQNm2,
                    motionChild: true,
                    nodeId: "FHNFMCMOj",
                    openInNewTab: true,
                    scopeId: "Pciq_WaHS",
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-s36am5",className,classNames)} framer-be1nbu`,
                        "data-framer-name": "Default",
                        layoutDependency: layoutDependency,
                        layoutId: "FHNFMCMOj",
                        ref: refBinding,
                        style: {
                            backgroundColor: "rgb(255, 255, 255)",
                            borderBottomLeftRadius: 10,
                            borderBottomRightRadius: 10,
                            borderTopLeftRadius: 10,
                            borderTopRightRadius: 10,
                            ...style
                        },
                        variants: {
                            Yp5vSngnR: {
                                backgroundColor: "rgb(0, 0, 0)"
                            }
                        },
                        ...addPropertyOverrides({
                            "FHNFMCMOj-hover": {
                                "data-framer-name": undefined
                            },
                            "Yp5vSngnR-hover": {
                                "data-framer-name": undefined
                            },
                            Yp5vSngnR: {
                                "data-framer-name": "Primary"
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-cb7f8n",
                            "data-framer-name": "Inner",
                            layoutDependency: layoutDependency,
                            layoutId: "mGiLbjhtZ",
                            children: [ /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        dir: "auto",
                                        style: {
                                            "--font-selector": "R0Y7R2Vpc3QtNjAw",
                                            "--framer-font-family": '"Geist", "Geist Placeholder", sans-serif',
                                            "--framer-font-size": "13px",
                                            "--framer-font-weight": "600",
                                            "--framer-letter-spacing": "0px",
                                            "--framer-line-height": "120%",
                                            "--framer-text-transform": "inherit"
                                        },
                                        children: "Title"
                                    })
                                }),
                                className: "framer-17a0e41",
                                fonts: ["GF;Geist-600"],
                                layoutDependency: layoutDependency,
                                layoutId: "F4C7DRhMx",
                                text: tmJjEwoTa,
                                variants: {
                                    Yp5vSngnR: {
                                        "--extracted-r6o4lv": "rgb(255, 255, 255)"
                                    }
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                                ...addPropertyOverrides({
                                    Yp5vSngnR: {
                                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                                            children: /*#__PURE__*/ _jsx(motion.p, {
                                                dir: "auto",
                                                style: {
                                                    "--font-selector": "R0Y7R2Vpc3QtNjAw",
                                                    "--framer-font-family": '"Geist", "Geist Placeholder", sans-serif',
                                                    "--framer-font-size": "13px",
                                                    "--framer-font-weight": "600",
                                                    "--framer-letter-spacing": "0px",
                                                    "--framer-line-height": "120%",
                                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                                                    "--framer-text-transform": "inherit"
                                                },
                                                children: "Title"
                                            })
                                        })
                                    }
                                }, baseVariant, gestureVariant)
                            }), /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        dir: "auto",
                                        style: {
                                            "--font-selector": "R0Y7R2Vpc3QtNjAw",
                                            "--framer-font-family": '"Geist", "Geist Placeholder", sans-serif',
                                            "--framer-font-size": "13px",
                                            "--framer-font-weight": "600",
                                            "--framer-letter-spacing": "0px",
                                            "--framer-line-height": "120%",
                                            "--framer-text-transform": "inherit"
                                        },
                                        children: "Hover"
                                    })
                                }),
                                className: "framer-6p4yg7",
                                fonts: ["GF;Geist-600"],
                                layoutDependency: layoutDependency,
                                layoutId: "wLGu1LbOB",
                                text: zZgakqIy2,
                                variants: {
                                    Yp5vSngnR: {
                                        "--extracted-r6o4lv": "rgb(255, 255, 255)"
                                    }
                                },
                                verticalAlignment: "top",
                                withExternalLayout: true,
                                ...addPropertyOverrides({
                                    Yp5vSngnR: {
                                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                                            children: /*#__PURE__*/ _jsx(motion.p, {
                                                dir: "auto",
                                                style: {
                                                    "--font-selector": "R0Y7R2Vpc3QtNjAw",
                                                    "--framer-font-family": '"Geist", "Geist Placeholder", sans-serif',
                                                    "--framer-font-size": "13px",
                                                    "--framer-font-weight": "600",
                                                    "--framer-letter-spacing": "0px",
                                                    "--framer-line-height": "120%",
                                                    "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                                                    "--framer-text-transform": "inherit"
                                                },
                                                children: "Hover"
                                            })
                                        })
                                    }
                                }, baseVariant, gestureVariant)
                            })]
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-ohfFP.framer-be1nbu, .framer-ohfFP .framer-be1nbu { display: block; }", ".framer-ohfFP.framer-s36am5 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 36px; justify-content: center; overflow: visible; padding: 10px; position: relative; text-decoration: none; width: 136px; }", ".framer-ohfFP .framer-cb7f8n { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 16px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1px; }", ".framer-ohfFP .framer-17a0e41, .framer-ohfFP .framer-6p4yg7 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-ohfFP.framer-v-s36am5.hover .framer-cb7f8n, .framer-ohfFP.framer-v-5vx8oy.hover .framer-cb7f8n { justify-content: flex-end; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 36
 * @framerIntrinsicWidth 136
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Yp5vSngnR":{"layout":["fixed","fixed"]},"BWxKd0Lac":{"layout":["fixed","fixed"]},"Uk6LejiTu":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"tmJjEwoTa":"title","zZgakqIy2":"titleHover","bF1RjQNm2":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerPciq_WaHS = withCSS(Component, css, "framer-ohfFP");
export default FramerPciq_WaHS;
FramerPciq_WaHS.displayName = "Buy Budges/Badge";
FramerPciq_WaHS.defaultProps = {
    height: 36,
    width: 136
};
addPropertyControls(FramerPciq_WaHS, {
    variant: {
        options: ["FHNFMCMOj", "Yp5vSngnR"],
        optionTitles: ["Default", "Primary"],
        title: "Variant",
        type: ControlType.Enum
    },
    tmJjEwoTa: {
        defaultValue: "Title",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    ontmJjEwoTaChange: {
        changes: "tmJjEwoTa",
        type: ControlType.ChangeHandler
    },
    zZgakqIy2: {
        defaultValue: "Hover",
        description: "",
        displayTextArea: false,
        title: "Title Hover",
        type: ControlType.String
    },
    onzZgakqIy2Change: {
        changes: "zZgakqIy2",
        type: ControlType.ChangeHandler
    },
    bF1RjQNm2: {
        title: "Link",
        type: ControlType.Link
    }
});
addFonts(FramerPciq_WaHS, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Geist",
        source: "google",
        style: "normal",
        uiFamilyName: "Geist",
        url: "https://fonts.gstatic.com/s/geist/v5/gyBhhwUxId8gMGYQMKR3pzfaWI_RQuQ4mJPby1QNtA.woff2",
        weight: "600"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerPciq_WaHS",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"tmJjEwoTa\":\"title\",\"zZgakqIy2\":\"titleHover\",\"bF1RjQNm2\":\"link\"}",
                "framerIntrinsicWidth": "136",
                "framerIntrinsicHeight": "36",
                "framerContractVersion": "1",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"Yp5vSngnR\":{\"layout\":[\"fixed\",\"fixed\"]},\"BWxKd0Lac\":{\"layout\":[\"fixed\",\"fixed\"]},\"Uk6LejiTu\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerImmutableVariables": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./Pciq_WaHS.map