// Generated by Framer (890879b)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    Link,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Icon1 from "https://framerusercontent.com/modules/CLgurHPTFgmtXE5jBvY3/catcT59hcyvCZvC4nIST/tHhsEfhOY.js";
const enabledGestures = {
    CgC0O4B6T: {
        hover: true
    },
    ttblwCTt9: {
        hover: true
    }
};
const cycleOrder = ["CgC0O4B6T", "ttblwCTt9"];
const serializationHash = "framer-UOzJC";
const variantClassNames = {
    CgC0O4B6T: "framer-v-1c55di8",
    ttblwCTt9: "framer-v-1rp1dk9"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Default: "CgC0O4B6T",
    Inverse: "ttblwCTt9"
};
const getProps = ({
    height,
    icon,
    id,
    link,
    newTab,
    width,
    ...props
}) => {
    return { ...props,
        dq_k2dxEu: newTab ? ? props.dq_k2dxEu ? ? true,
        m74Cti_iF: link ? ? props.m74Cti_iF,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "CgC0O4B6T",
        zzzhuZcyF: icon ? ? props.zzzhuZcyF ? ? Icon1
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        zzzhuZcyF,
        m74Cti_iF,
        dq_k2dxEu,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "CgC0O4B6T",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const Icon = zzzhuZcyF;
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: m74Cti_iF,
                    motionChild: true,
                    nodeId: "CgC0O4B6T",
                    openInNewTab: dq_k2dxEu,
                    scopeId: "jsHR4pRPA",
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-1c55di8",className,classNames)} framer-g6jk2u`,
                        "data-framer-name": "Default",
                        layoutDependency: layoutDependency,
                        layoutId: "CgC0O4B6T",
                        ref: refBinding,
                        style: { ...style
                        },
                        ...addPropertyOverrides({
                            "CgC0O4B6T-hover": {
                                "data-framer-name": undefined
                            },
                            "ttblwCTt9-hover": {
                                "data-framer-name": undefined
                            },
                            ttblwCTt9: {
                                "data-framer-name": "Inverse"
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(Icon, {
                            animated: true,
                            className: "framer-bfd1jy",
                            layoutDependency: layoutDependency,
                            layoutId: "sN2RaASSq",
                            style: {
                                "--21h8s6": "var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, rgb(26, 28, 24))"
                            },
                            variants: {
                                ttblwCTt9: {
                                    "--21h8s6": "var(--token-c5446a54-80de-4f79-b24b-55997bf1fe5e, rgb(255, 255, 255))"
                                }
                            }
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-UOzJC.framer-g6jk2u, .framer-UOzJC .framer-g6jk2u { display: block; }", ".framer-UOzJC.framer-1c55di8 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 20px; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 20px; }", ".framer-UOzJC .framer-bfd1jy { flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 20px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 20
 * @framerIntrinsicWidth 20
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"ttblwCTt9":{"layout":["fixed","fixed"]},"vUB5YIHcG":{"layout":["fixed","fixed"]},"Aut28ZwBL":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"zzzhuZcyF":"icon","m74Cti_iF":"link","dq_k2dxEu":"newTab"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerVectorSets ["omX0gWFPqDwhaiWwf6ab"]
 */
const FramerjsHR4pRPA = withCSS(Component, css, "framer-UOzJC");
export default FramerjsHR4pRPA;
FramerjsHR4pRPA.displayName = "Components/Social Icon";
FramerjsHR4pRPA.defaultProps = {
    height: 20,
    width: 20
};
addPropertyControls(FramerjsHR4pRPA, {
    variant: {
        options: ["CgC0O4B6T", "ttblwCTt9"],
        optionTitles: ["Default", "Inverse"],
        title: "Variant",
        type: ControlType.Enum
    },
    zzzhuZcyF: {
        defaultValue: {
            identifier: "module:CLgurHPTFgmtXE5jBvY3/catcT59hcyvCZvC4nIST/tHhsEfhOY.js:default",
            moduleId: "CLgurHPTFgmtXE5jBvY3"
        },
        setModuleId: "omX0gWFPqDwhaiWwf6ab",
        title: "Icon",
        type: ControlType.VectorSetItem
    },
    m74Cti_iF: {
        title: "Link",
        type: ControlType.Link
    },
    dq_k2dxEu: {
        defaultValue: true,
        title: "New Tab",
        type: ControlType.Boolean
    }
});
addFonts(FramerjsHR4pRPA, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerjsHR4pRPA",
            "slots": [],
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerIntrinsicHeight": "20",
                "framerColorSyntax": "true",
                "framerVariables": "{\"zzzhuZcyF\":\"icon\",\"m74Cti_iF\":\"link\",\"dq_k2dxEu\":\"newTab\"}",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"ttblwCTt9\":{\"layout\":[\"fixed\",\"fixed\"]},\"vUB5YIHcG\":{\"layout\":[\"fixed\",\"fixed\"]},\"Aut28ZwBL\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerIntrinsicWidth": "20",
                "framerComponentViewportWidth": "true",
                "framerImmutableVariables": "true",
                "framerDisplayContentsDiv": "false",
                "framerVectorSets": "[\"omX0gWFPqDwhaiWwf6ab\"]",
                "framerContractVersion": "1"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./jsHR4pRPA.map